version: 2

sources:
  - name: raw
    database: greenweez-507113
    schema: gz_raw_data
    description: "Greenweez ham veri tabloları - sepet analizi kaynağı"
    tables:
      - name: sales
        identifier: raw_gz_sales
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship